//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.06 at 07:29:07 PM MEZ 
//


package de.uniluebeck.itm.tcp.Server.JaxbDevices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.uniluebeck.itm.tcp.Server.JaxbDevices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JaxbDeviceList_QNAME = new QName("rpc_pro/rpcPrototype/schema/devices", "jaxbDeviceList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.uniluebeck.itm.tcp.Server.JaxbDevices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JaxbSensors }
     * 
     */
    public JaxbSensors createJaxbSensors() {
        return new JaxbSensors();
    }

    /**
     * Create an instance of {@link JaxbDeviceList }
     * 
     */
    public JaxbDeviceList createJaxbDeviceList() {
        return new JaxbDeviceList();
    }

    /**
     * Create an instance of {@link JaxbDevice }
     * 
     */
    public JaxbDevice createJaxbDevice() {
        return new JaxbDevice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JaxbDeviceList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "rpc_pro/rpcPrototype/schema/devices", name = "jaxbDeviceList")
    public JAXBElement<JaxbDeviceList> createJaxbDeviceList(JaxbDeviceList value) {
        return new JAXBElement<JaxbDeviceList>(_JaxbDeviceList_QNAME, JaxbDeviceList.class, null, value);
    }

}
