//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.13 at 05:03:20 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "de/uniluebeck/itm/schema/devices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.uniluebeck.itm.tcp.Server.JaxbDevices;
