//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.06 at 07:29:07 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "rpc_pro/rpcPrototype/schema/devices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.uniluebeck.itm.tcp.Server.JaxbDevices;
