//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.02 at 06:00:17 PM MEZ 
//


package rpc_pro.rpcPrototype.Server.Devices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rpc_pro.rpcPrototype.Server.Devices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeviceList_QNAME = new QName("rpc_pro/rpcPrototype/schema/devices", "DeviceList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rpc_pro.rpcPrototype.Server.Devices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeviceList }
     * 
     */
    public DeviceList createDeviceList() {
        return new DeviceList();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Sensors }
     * 
     */
    public Sensors createSensors() {
        return new Sensors();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeviceList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "rpc_pro/rpcPrototype/schema/devices", name = "DeviceList")
    public JAXBElement<DeviceList> createDeviceList(DeviceList value) {
        return new JAXBElement<DeviceList>(_DeviceList_QNAME, DeviceList.class, null, value);
    }

}
