// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package rpc_pro.rpcPrototype.files;

public final class MessageServiceFiles {
  private MessageServiceFiles() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class VOID extends
      com.google.protobuf.GeneratedMessage {
    // Use VOID.newBuilder() to construct.
    private VOID() {
      initFields();
    }
    private VOID(boolean noInit) {}
    
    private static final VOID defaultInstance;
    public static VOID getDefaultInstance() {
      return defaultInstance;
    }
    
    public VOID getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_VOID_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_VOID_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID result;
      
      // Construct using rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID();
        return builder;
      }
      
      protected rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDescriptor();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID getDefaultInstanceForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID) {
          return mergeFrom((rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID other) {
        if (other == rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:VOID)
    }
    
    static {
      defaultInstance = new VOID(true);
      rpc_pro.rpcPrototype.files.MessageServiceFiles.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:VOID)
  }
  
  public static final class Message extends
      com.google.protobuf.GeneratedMessage {
    // Use Message.newBuilder() to construct.
    private Message() {
      initFields();
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_Message_fieldAccessorTable;
    }
    
    // required string query = 1;
    public static final int QUERY_FIELD_NUMBER = 1;
    private boolean hasQuery;
    private java.lang.String query_ = "";
    public boolean hasQuery() { return hasQuery; }
    public java.lang.String getQuery() { return query_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasQuery) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasQuery()) {
        output.writeString(1, getQuery());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasQuery()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getQuery());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc_pro.rpcPrototype.files.MessageServiceFiles.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.Message result;
      
      // Construct using rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.Message();
        return builder;
      }
      
      protected rpc_pro.rpcPrototype.files.MessageServiceFiles.Message internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.Message();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDescriptor();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message getDefaultInstanceForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rpc_pro.rpcPrototype.files.MessageServiceFiles.Message returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc_pro.rpcPrototype.files.MessageServiceFiles.Message) {
          return mergeFrom((rpc_pro.rpcPrototype.files.MessageServiceFiles.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc_pro.rpcPrototype.files.MessageServiceFiles.Message other) {
        if (other == rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          setQuery(other.getQuery());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setQuery(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string query = 1;
      public boolean hasQuery() {
        return result.hasQuery();
      }
      public java.lang.String getQuery() {
        return result.getQuery();
      }
      public Builder setQuery(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasQuery = true;
        result.query_ = value;
        return this;
      }
      public Builder clearQuery() {
        result.hasQuery = false;
        result.query_ = getDefaultInstance().getQuery();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Message)
    }
    
    static {
      defaultInstance = new Message(true);
      rpc_pro.rpcPrototype.files.MessageServiceFiles.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Message)
  }
  
  public static final class HandleReturns extends
      com.google.protobuf.GeneratedMessage {
    // Use HandleReturns.newBuilder() to construct.
    private HandleReturns() {
      initFields();
    }
    private HandleReturns(boolean noInit) {}
    
    private static final HandleReturns defaultInstance;
    public static HandleReturns getDefaultInstance() {
      return defaultInstance;
    }
    
    public HandleReturns getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_HandleReturns_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_HandleReturns_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns result;
      
      // Construct using rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns();
        return builder;
      }
      
      protected rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns.getDescriptor();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns getDefaultInstanceForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns) {
          return mergeFrom((rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns other) {
        if (other == rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:HandleReturns)
    }
    
    static {
      defaultInstance = new HandleReturns(true);
      rpc_pro.rpcPrototype.files.MessageServiceFiles.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HandleReturns)
  }
  
  public static final class Identification extends
      com.google.protobuf.GeneratedMessage {
    // Use Identification.newBuilder() to construct.
    private Identification() {
      initFields();
    }
    private Identification(boolean noInit) {}
    
    private static final Identification defaultInstance;
    public static Identification getDefaultInstance() {
      return defaultInstance;
    }
    
    public Identification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_Identification_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_Identification_fieldAccessorTable;
    }
    
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private boolean hasUsername;
    private java.lang.String username_ = "";
    public boolean hasUsername() { return hasUsername; }
    public java.lang.String getUsername() { return username_; }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private boolean hasPassword;
    private java.lang.String password_ = "";
    public boolean hasPassword() { return hasPassword; }
    public java.lang.String getPassword() { return password_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasUsername) return false;
      if (!hasPassword) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasUsername()) {
        output.writeString(1, getUsername());
      }
      if (hasPassword()) {
        output.writeString(2, getPassword());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUsername()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUsername());
      }
      if (hasPassword()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPassword());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification result;
      
      // Construct using rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification();
        return builder;
      }
      
      protected rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.getDescriptor();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification getDefaultInstanceForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification) {
          return mergeFrom((rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification other) {
        if (other == rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setUsername(input.readString());
              break;
            }
            case 18: {
              setPassword(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string username = 1;
      public boolean hasUsername() {
        return result.hasUsername();
      }
      public java.lang.String getUsername() {
        return result.getUsername();
      }
      public Builder setUsername(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUsername = true;
        result.username_ = value;
        return this;
      }
      public Builder clearUsername() {
        result.hasUsername = false;
        result.username_ = getDefaultInstance().getUsername();
        return this;
      }
      
      // required string password = 2;
      public boolean hasPassword() {
        return result.hasPassword();
      }
      public java.lang.String getPassword() {
        return result.getPassword();
      }
      public Builder setPassword(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPassword = true;
        result.password_ = value;
        return this;
      }
      public Builder clearPassword() {
        result.hasPassword = false;
        result.password_ = getDefaultInstance().getPassword();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Identification)
    }
    
    static {
      defaultInstance = new Identification(true);
      rpc_pro.rpcPrototype.files.MessageServiceFiles.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Identification)
  }
  
  public static final class ProgramPacket extends
      com.google.protobuf.GeneratedMessage {
    // Use ProgramPacket.newBuilder() to construct.
    private ProgramPacket() {
      initFields();
    }
    private ProgramPacket(boolean noInit) {}
    
    private static final ProgramPacket defaultInstance;
    public static ProgramPacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProgramPacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_ProgramPacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.internal_static_ProgramPacket_fieldAccessorTable;
    }
    
    // repeated bytes BinaryPacket = 1;
    public static final int BINARYPACKET_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> binaryPacket_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getBinaryPacketList() {
      return binaryPacket_;
    }
    public int getBinaryPacketCount() { return binaryPacket_.size(); }
    public com.google.protobuf.ByteString getBinaryPacket(int index) {
      return binaryPacket_.get(index);
    }
    
    // optional int64 timeout = 2;
    public static final int TIMEOUT_FIELD_NUMBER = 2;
    private boolean hasTimeout;
    private long timeout_ = 0L;
    public boolean hasTimeout() { return hasTimeout; }
    public long getTimeout() { return timeout_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.google.protobuf.ByteString element : getBinaryPacketList()) {
        output.writeBytes(1, element);
      }
      if (hasTimeout()) {
        output.writeInt64(2, getTimeout());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getBinaryPacketList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getBinaryPacketList().size();
      }
      if (hasTimeout()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimeout());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket result;
      
      // Construct using rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket();
        return builder;
      }
      
      protected rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.getDescriptor();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket getDefaultInstanceForType() {
        return rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.binaryPacket_ != java.util.Collections.EMPTY_LIST) {
          result.binaryPacket_ =
            java.util.Collections.unmodifiableList(result.binaryPacket_);
        }
        rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket) {
          return mergeFrom((rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket other) {
        if (other == rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.getDefaultInstance()) return this;
        if (!other.binaryPacket_.isEmpty()) {
          if (result.binaryPacket_.isEmpty()) {
            result.binaryPacket_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.binaryPacket_.addAll(other.binaryPacket_);
        }
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              addBinaryPacket(input.readBytes());
              break;
            }
            case 16: {
              setTimeout(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // repeated bytes BinaryPacket = 1;
      public java.util.List<com.google.protobuf.ByteString> getBinaryPacketList() {
        return java.util.Collections.unmodifiableList(result.binaryPacket_);
      }
      public int getBinaryPacketCount() {
        return result.getBinaryPacketCount();
      }
      public com.google.protobuf.ByteString getBinaryPacket(int index) {
        return result.getBinaryPacket(index);
      }
      public Builder setBinaryPacket(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.binaryPacket_.set(index, value);
        return this;
      }
      public Builder addBinaryPacket(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.binaryPacket_.isEmpty()) {
          result.binaryPacket_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.binaryPacket_.add(value);
        return this;
      }
      public Builder addAllBinaryPacket(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.binaryPacket_.isEmpty()) {
          result.binaryPacket_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.binaryPacket_);
        return this;
      }
      public Builder clearBinaryPacket() {
        result.binaryPacket_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int64 timeout = 2;
      public boolean hasTimeout() {
        return result.hasTimeout();
      }
      public long getTimeout() {
        return result.getTimeout();
      }
      public Builder setTimeout(long value) {
        result.hasTimeout = true;
        result.timeout_ = value;
        return this;
      }
      public Builder clearTimeout() {
        result.hasTimeout = false;
        result.timeout_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProgramPacket)
    }
    
    static {
      defaultInstance = new ProgramPacket(true);
      rpc_pro.rpcPrototype.files.MessageServiceFiles.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProgramPacket)
  }
  
  public static abstract class TestOperations
      implements com.google.protobuf.Service {
    protected TestOperations() {}
    
    public interface Interface {
      public abstract void setMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done);
      
      public abstract void getMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TestOperations() {
        @Override
        public  void setMessage(
            com.google.protobuf.RpcController controller,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message request,
            com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done) {
          impl.setMessage(controller, request, done);
        }
        
        @Override
        public  void getMessage(
            com.google.protobuf.RpcController controller,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
            com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done) {
          impl.getMessage(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.setMessage(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.Message)request);
            case 1:
              return impl.getMessage(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
            case 1:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
            case 1:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void setMessage(
        com.google.protobuf.RpcController controller,
        rpc_pro.rpcPrototype.files.MessageServiceFiles.Message request,
        com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done);
    
    public abstract void getMessage(
        com.google.protobuf.RpcController controller,
        rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
        com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.setMessage(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.Message)request,
            com.google.protobuf.RpcUtil.<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID>specializeCallback(
              done));
          return;
        case 1:
          this.getMessage(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID)request,
            com.google.protobuf.RpcUtil.<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
        case 1:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
        case 1:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends rpc_pro.rpcPrototype.files.MessageServiceFiles.TestOperations implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void setMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.class,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance()));
      }
      
      public  void getMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.class,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID setMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message request)
          throws com.google.protobuf.ServiceException;
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message getMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID setMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message request)
          throws com.google.protobuf.ServiceException {
        return (rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance());
      }
      
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message getMessage(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request)
          throws com.google.protobuf.ServiceException {
        return (rpc_pro.rpcPrototype.files.MessageServiceFiles.Message) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance());
      }
      
    }
  }
  
  public static abstract class Operations
      implements com.google.protobuf.Service {
    protected Operations() {}
    
    public interface Interface {
      public abstract void connect(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done);
      
      public abstract void program(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done);
      
      public abstract void getState(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Operations() {
        @Override
        public  void connect(
            com.google.protobuf.RpcController controller,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification request,
            com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done) {
          impl.connect(controller, request, done);
        }
        
        @Override
        public  void program(
            com.google.protobuf.RpcController controller,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket request,
            com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done) {
          impl.program(controller, request, done);
        }
        
        @Override
        public  void getState(
            com.google.protobuf.RpcController controller,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
            com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done) {
          impl.getState(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.connect(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification)request);
            case 1:
              return impl.program(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket)request);
            case 2:
              return impl.getState(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.getDefaultInstance();
            case 1:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.getDefaultInstance();
            case 2:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
            case 1:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
            case 2:
              return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void connect(
        com.google.protobuf.RpcController controller,
        rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification request,
        com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done);
    
    public abstract void program(
        com.google.protobuf.RpcController controller,
        rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket request,
        com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done);
    
    public abstract void getState(
        com.google.protobuf.RpcController controller,
        rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
        com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.getDescriptor().getServices().get(1);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.connect(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification)request,
            com.google.protobuf.RpcUtil.<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message>specializeCallback(
              done));
          return;
        case 1:
          this.program(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket)request,
            com.google.protobuf.RpcUtil.<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID>specializeCallback(
              done));
          return;
        case 2:
          this.getState(controller, (rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID)request,
            com.google.protobuf.RpcUtil.<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.getDefaultInstance();
        case 1:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.getDefaultInstance();
        case 2:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
        case 1:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance();
        case 2:
          return rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends rpc_pro.rpcPrototype.files.MessageServiceFiles.Operations implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void connect(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.class,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance()));
      }
      
      public  void program(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.class,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance()));
      }
      
      public  void getState(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request,
          com.google.protobuf.RpcCallback<rpc_pro.rpcPrototype.files.MessageServiceFiles.Message> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.class,
            rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message connect(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification request)
          throws com.google.protobuf.ServiceException;
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID program(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket request)
          throws com.google.protobuf.ServiceException;
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message getState(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message connect(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification request)
          throws com.google.protobuf.ServiceException {
        return (rpc_pro.rpcPrototype.files.MessageServiceFiles.Message) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance());
      }
      
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID program(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket request)
          throws com.google.protobuf.ServiceException {
        return (rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.getDefaultInstance());
      }
      
      
      public rpc_pro.rpcPrototype.files.MessageServiceFiles.Message getState(
          com.google.protobuf.RpcController controller,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID request)
          throws com.google.protobuf.ServiceException {
        return (rpc_pro.rpcPrototype.files.MessageServiceFiles.Message) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.getDefaultInstance());
      }
      
    }
  }
  
  public static abstract class PacketService
      implements com.google.protobuf.Service {
    protected PacketService() {}
    
    public interface Interface {
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PacketService() {
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return rpc_pro.rpcPrototype.files.MessageServiceFiles.getDescriptor().getServices().get(2);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends rpc_pro.rpcPrototype.files.MessageServiceFiles.PacketService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {}
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VOID_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VOID_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HandleReturns_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HandleReturns_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Identification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Identification_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProgramPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProgramPacket_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pingpong.proto\"\006\n\004VOID\"\030\n\007Message\022\r\n\005q" +
      "uery\030\001 \002(\t\"\017\n\rHandleReturns\"4\n\016Identific" +
      "ation\022\020\n\010username\030\001 \002(\t\022\020\n\010password\030\002 \002(" +
      "\t\"6\n\rProgramPacket\022\024\n\014BinaryPacket\030\001 \003(\014" +
      "\022\017\n\007timeout\030\002 \001(\0032N\n\016TestOperations\022\035\n\ns" +
      "etMessage\022\010.Message\032\005.VOID\022\035\n\ngetMessage" +
      "\022\005.VOID\032\010.Message2q\n\nOperations\022$\n\007conne" +
      "ct\022\017.Identification\032\010.Message\022 \n\007program" +
      "\022\016.ProgramPacket\032\005.VOID\022\033\n\010getState\022\005.VO" +
      "ID\032\010.Message2\017\n\rPacketServiceB1\n\032rpc_pro",
      ".rpcPrototype.filesB\023MessageServiceFiles"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_VOID_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_VOID_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VOID_descriptor,
              new java.lang.String[] { },
              rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.class,
              rpc_pro.rpcPrototype.files.MessageServiceFiles.VOID.Builder.class);
          internal_static_Message_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Message_descriptor,
              new java.lang.String[] { "Query", },
              rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.class,
              rpc_pro.rpcPrototype.files.MessageServiceFiles.Message.Builder.class);
          internal_static_HandleReturns_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_HandleReturns_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HandleReturns_descriptor,
              new java.lang.String[] { },
              rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns.class,
              rpc_pro.rpcPrototype.files.MessageServiceFiles.HandleReturns.Builder.class);
          internal_static_Identification_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Identification_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Identification_descriptor,
              new java.lang.String[] { "Username", "Password", },
              rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.class,
              rpc_pro.rpcPrototype.files.MessageServiceFiles.Identification.Builder.class);
          internal_static_ProgramPacket_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ProgramPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProgramPacket_descriptor,
              new java.lang.String[] { "BinaryPacket", "Timeout", },
              rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.class,
              rpc_pro.rpcPrototype.files.MessageServiceFiles.ProgramPacket.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
